[tool.poetry]
name = "xcodeproj"
version = "0.11.1"
description = "A utility for interacting with Xcode's xcodeproj bundle format."

license = "MIT"

authors = [
    "Dale Myers <dalemy@microsoft.com>"
]

readme = 'README.md'

repository = "https://github.com/Microsoft/xcodeproj"
homepage = "https://github.com/Microsoft/xcodeproj"

keywords = ['app center', 'api']

classifiers = [
    'Development Status :: 3 - Alpha',
    'Intended Audience :: Developers',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Topic :: Software Development',
    'Topic :: Utilities'
]

[tool.poetry.dependencies]
python = "^3.7"
appdirs = "^1.0"
deserialize = "^1.8.0"

[tool.poetry.dev-dependencies]
black = "=20.8b1"
mypy = "=0.800"
pylint = "=2.6.0"
pytest = "=6.2.2"
pytest-cov = "=2.11.1"
requests = "^2.25.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
